#ifndef LOG_CATEGORY_HPP_INCLUDED
#define LOG_CATEGORY_HPP_INCLUDED

enum class LogCategory : unsigned short {
    none = 0,
    apuAll = 0x100,
    apuTriangle,
    apuPulse1,
    apuPulse2,
    apuNoise,
    apuDMC,
    apuWriteMem,
    apuReadMem,
    apuWrite4001,
    apuWrite4008,
    apuWrite400A,
    apuWrite400B,
    apuWrite400E,
    apuWrite4010,
    apuWrite4015,
    apuMemReader,
    apuHalfFrame,
    apuQuarterFrame,
    cpuAll = 0x200,
    cpuLogger,
    cpuPreciseTime,
    cpuRun,
    cpuOpcodes,
    inputAll = 0x300,
    loaderAll = 0x400,
    loaderCart,
    loaderNSF,
    mapperAll = 0x500,
    mapperAXROM,
    mapperBasic,
    mapperCNROM,
    mapperGXROM,
    mapperMemoryMapper,
    mapperMMC1,
    mapperMMC2,
    mapperMMC3,
    mapperUXROM,
    mapperNSF,
    onessamaAll = 0x600,
    onessamaMain,
    onessama8Tunes,
    onessamaCore,
    onessamaLibretro,
    ppuAll = 0x700,
    ppuRender,
    ppuRendSprColor,
    ppuRendTransp,
    ppuRendSprPalFront,
    ppuSetOAM,
    ppuGetOAM,
    ppuSprEvalSecClear,
    ppuSprEvalStarts,
    ppuSprEvalOdd,
    ppuSprEvalEven,
    ppuFetchOamLow,
    ppuFetchOamHigh,
    ppuWriteMem,
    ppuReadMem,
    ppuProcess,
    ppuTriggerNMI,
    ppuWrite2000,
    ppuWrite2001,
    ppuRead2002,
    ppuWrite2004,
    ppuWrite2005,
    ppuWrite2006,
    ppuWrite2007,
    otherAll = 0x800,
    otherLogger,
    otherRetroAudio,
    otherRetroGraphics,

    // SUBSECTION_MASK = 0x00FF,
    // SECTION_MASK = 0xF00,
};

const char* logCategoryToString(LogCategory category) noexcept;

#endif // LOG_CATEGORY_HPP_INCLUDED
